
- name: Install package
  apt:
    name: "{{ package_name }}"
    state: present
  register: install_result
  changed_when: 1 == 1
  notify:
    - Copy files using loop

- name: Copy index.html using template
  template:
    src: "{{ template_name }}"
    dest: /var/www/html/index.html
  notify:
    - Restart service