- name: Restart service
  service:
    name: "{{ package_name }}"
    state: restarted

- name: Copy files using loop
  copy:
    src: "{{ item }}"
    dest: "/var/www/html/{{ item }}"
  loop: "{{ file_list }}"
  notify:
    - Restart service